server:
  port: 1300
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/johnyu666/config-center.git
          lable: main #git分支


  #  加入此配置，配置中心会向注册到MQ的一个Channel，当我们post 到bus-refresh端点时，会将github上变动的信息发送到此Channel上
  #  此时订阅此Channel的Client就会收到此消息，进而完成"自动的"刷新配置的工作
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    host: localhost

# configer-server 会将actuator发布一个 'bus-refresh'的端点，我们需要将其暴露，然后使用以下命令：
# curl -v -X POST "http://localhost:1300/actuator/bus-refresh"
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh' # 通过发送一个post空请求到 /bus-refresh，结合客户端的@RefreshScope接收配置变化

# 启动MQ的方法：
## rabbit MQ的启动
#docker run -d --name my-rabbit --rm -p 5672:5672  rabbitmq:3

## mq manager的启动
#docker run -d --hostname my-rabbit --name some-rabbit --rm -p 15672:15672 rabbitmq:3-management
